# Generated by Django 5.0.4 on 2024-05-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=30)),
                ('book_author', models.CharField(default='N/A', max_length=15, null=True)),
                ('image', models.ImageField(upload_to='all_books/img')),
                ('book_file', models.FileField(upload_to='all_books')),
            ],
        ),
    ]
