# Generated by Django 5.0.4 on 2024-05-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_app', '0002_book_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_price',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=300, max_length=200),
            preserve_default=False,
        ),
    ]
